---
# Install k3s on the Raspberry Pi
- name: Download k3s installer script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Run k3s installer script
  command: /tmp/k3s-install.sh
