apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: "/config"
          name: plex-config
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-pvc
