---
# Security Hardening tasks

- name: Disable root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart SSH

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled

# New task to allow SSH through UFW
- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: ssh
    state: enabled

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
